// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0dmb1Dm3c2Z-GskW8fGwu2hH4IfqMLoY',
    appId: '1:20590588398:web:95b6bacb75612cdd729eff',
    messagingSenderId: '20590588398',
    projectId: 'springbootqrmanager',
    authDomain: 'springbootqrmanager.firebaseapp.com',
    storageBucket: 'springbootqrmanager.appspot.com',
    measurementId: 'G-VQ6C3SR0TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCTfInvYYsYPGgMUD4cR4HnC8SOrfeOUE',
    appId: '1:20590588398:android:9420028be914f24e729eff',
    messagingSenderId: '20590588398',
    projectId: 'springbootqrmanager',
    storageBucket: 'springbootqrmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO4kG4FNiqpuxvGeVtDwvHYWU3XztUWw4',
    appId: '1:20590588398:ios:075db8a3d0e32754729eff',
    messagingSenderId: '20590588398',
    projectId: 'springbootqrmanager',
    storageBucket: 'springbootqrmanager.appspot.com',
    iosBundleId: 'com.example.springApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO4kG4FNiqpuxvGeVtDwvHYWU3XztUWw4',
    appId: '1:20590588398:ios:075db8a3d0e32754729eff',
    messagingSenderId: '20590588398',
    projectId: 'springbootqrmanager',
    storageBucket: 'springbootqrmanager.appspot.com',
    iosBundleId: 'com.example.springApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0dmb1Dm3c2Z-GskW8fGwu2hH4IfqMLoY',
    appId: '1:20590588398:web:b7f955a8a478b6bb729eff',
    messagingSenderId: '20590588398',
    projectId: 'springbootqrmanager',
    authDomain: 'springbootqrmanager.firebaseapp.com',
    storageBucket: 'springbootqrmanager.appspot.com',
    measurementId: 'G-0D6S1RVZY8',
  );

}